### PR TITLE
Big rewrite for the pirate bay new API

### LINKED ISSUE #117: Configure request timeout in the config file
TPB site works, but it takes a really long time to respond. Increasing the timeout for the request would solve this issue.

### LINKED ISSUE #125: JSON output for results
Can you implement JSON output of all results?

like, name, hash, seeds, peers, etc, and full magnet link

Thank you

### LINKED ISSUE #134: Many mirrors have an incompatible interface
Even on working mirror urls getting blocked mirror detected.

### PR DESCRIPTION
**Pull request by rnhmjoj**
Fix #134, #135.

#### To do:
 - [x] implement "browse" mode
 - [x] implement pagination
 - [x] test everything again

#### Done
 - [x] Implement search
 - [x] implement categories
 - [x] implement "sort by"
 - [x] implement "recent"

I also did some other work on
- Add JSON output option: fix #125 
- Add timeout option: fix #117

### CODE REVIEW

**Comment by bignellrp** [comment]
Search works nicely but I’m getting an error with saving the file. I’m not sure if this is my fault. I tried pip3 install but was still getting version 0.3.7 so I cloned them api branch into a folder and copied the pirate folder over the top of .local/lib/python3.6/site-packages/pirate/

Now I get this error:

Saving selected torrents...
Traceback (most recent call last):
  File "/home/rbignell/.local/bin/pirate-get", line 11, in <module>
    sys.exit(main())
  File "/home/rbignell/.local/lib/python3.6/site-packages/pirate/pirate.py", line 471, in main
    pirate_main(args)
  File "/home/rbignell/.local/lib/python3.6/site-packages/pirate/pirate.py", line 450, in pirate_main
    results, args.save_directory)
TypeError: save_torrents() missing 1 required positional argument: 'timeout'

**Comment by rnhmjoj** [comment]
No, it's not your fault: you spotted a mistaked. I fixed it, thank you.
However saving torrents doesn't work, still: the feature is based on http://itorrents.org which has started blocking non-javascript user agents. I don't want to play cat and mouse with cloudflare so we should find another less hostile caching service. If you have any suggestion I would happily try it out.

**Comment by rnhmjoj** [comment]
I figured out the browse mode. The last thing would be pagination.

**Comment by rnhmjoj** [comment]
Done. However there seems to be no way to get more pages for searches, only for recent torrents.
Since the site itself doesn't do it anymore I think it's either well hidden or gone for good.

**Comment by vikstrous** [comment]
@rnhmjoj I think it would be best if I transfer the pirate-get repo to you and give you access to push to pypi. I don't have sufficient free time and interest to continue maintaining pirate-get. Please make a  pypi account and send me your username so I can make the transfer. I'll also transfer the github repo and github will set up a redirect. If that doesn't work, I can replace this repo with a pointer to your copy.

**Comment by rnhmjoj** [comment]
I'm sorry to hear that. Unfortunately I don't have much time for pirate-get too but I can still keep up, Anyway, thank you for the offer. I'll do create a PyPI account for that but I'd prefer if you keep the repository: you have set up a number of useful integrations and I don't know how any of that work, currently.

**Comment by vikstrous** [comment]
Ok. Let me know your username. You already have full access to this repo, so you'll be able to do what you need to do for now. Check the wiki for instructions for how to do a release when you are ready to release.

**Comment by rnhmjoj** [comment]
Ok, so this is my account: https://pypi.org/user/rnhmjoj/. I haven't used PyPI in a while but the account still works.

**Comment by vikstrous** [comment]
I added you as owner. You can release whenever you want now.

**Comment by rnhmjoj** [comment]
Thank you!

**Comment by rnhmjoj** [comment]
I think I've tested it well enough: there may be still something but it's certainly better than the current state of master.

**Pull request merged**
