### PR TITLE
new interface for pirate-get

### PR DESCRIPTION
**Pull request by vikstrous**
#66

### CODE REVIEW

**Comment by vikstrous** [comment]
@rnhmjoj what are your thoughts on this?

**Comment by vikstrous** [comment]
@rnhmjoj do you think we should make this change? It's a pretty massive breaking change, so I don't want to do it unless other people think it's worth it.

**Comment by rnhmjoj** [comment]
wow, it's seems I have completely forgotten about this. I like the idea of subcommands. :+1:

**Comment by vikstrous** [comment]
This interface is much more scalable, but I usually run `pirate-get -t query` without needing a config file and this new interface makes simple use cases like that harder :( Maybe one day when I'm feeling ambitious and want to add more trackers I'll pick this up again... or if the pirate bay shuts down...

**Comment by vikstrous** [comment]
pirate-get has been stable for a while and it doesn't seem worth it to mess with it. I don't have the time or interest to rewrite all the cli parsing stuff, so I'll just close this.

**Pull request closed without merging**
