### PR TITLE
Allow users to set custom mirrors

### PR DESCRIPTION
**Pull request by rnhmjoj**
This should solve #31 and, partially, #59.

### CODE REVIEW

**Comment by vikstrous** [comment]
Awesome! LGTM

**Comment by vikstrous** [comment]
Oops sorry, just one thing: I would prefer commas over spaces to separate URLs because they are easier to pass on the command line. Up to you though.

**Comment by rnhmjoj** [comment]
I think a space is better since is not a valid character in a URL.

**Comment by vikstrous** [comment]
True. Okay, shipit.

On September 3, 2016 3:03:36 PM EDT, Michele Guerini Rocco <notifications@github.com> wrote:
>I think a space is better since is not a valid character in a URL.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/vikstrous/pirate-get/pull/89#issuecomment-244564173

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rnhmjoj** [comment]
Can you make a new release? There have been quite a few changes.

**Comment by vikstrous** [comment]
Yeah, sorry. I'll try to do one today.

On September 3, 2016 3:17:05 PM EDT, Michele Guerini Rocco <notifications@github.com> wrote:
>Can you make a new release? There have been quite a few changes.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/vikstrous/pirate-get/pull/89#issuecomment-244564891

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rnhmjoj** [comment]
Thank you

**Pull request merged**
