### PR TITLE
handle cookies for tpb http requests

### LINKED ISSUE #131: Mirrors all offline, should be able to specify target mirror URLs in config
All of the piratebay mirrors that pirate-get searches by default are offline, and there isn't an immediately obvious means to specify other mirrors to search, of which there are many. Does such a method of alternate mirror specification exist?

If it does not, then I would suggest adding one, as piratebay mirrors are being continually created and taken down, any static list will be rendered unusable sooner or later.

### PR DESCRIPTION
**Pull request by rnhmjoj**
The pirate bay (or a hoster in between) added a mechanism to rate-limit requests that forces us to handle cookies. This should fix #131.

### CODE REVIEW

**Comment by rnhmjoj** [comment]
I tested this with the pirate bay hidden service and it works. There are still 404 error in serveral mirrors, though.

**Comment by rnhmjoj** [comment]
The 503 error is cloudflare DoS protection, the 404s I get them even in a browser, safe to say those mirrors are broken.

**Comment by rnhmjoj** [comment]
I tested everything again: I can confirm the issue is fixed and we can do nothing about the other errors. I'm merging this since pirate-get it's pretty much broken right now.

**Comment by rnhmjoj** [comment]
@vikstrous can you make a release?

**Comment by vikstrous** [comment]
Releasing now. Sorry for the delay.

**Comment by rnhmjoj** [comment]
Thank you, no problem.

**Pull request merged**
