### PR TITLE
fix saving magents and torrents to a file

### LINKED ISSUE #95: default flag -T not clearly documented
When using the option to download the .torrent file as so

```shell
pirate-get -T 'ubuntu-1206'
```

Here's a dump of the trace
```trace
Saving selected torrents...
Traceback (most recent call last):
  File "/usr/local/bin/pirate-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/pirate/pirate.py", line 396, in main
    pirate_main(args)
  File "/usr/local/lib/python3.5/site-packages/pirate/pirate.py", line 377, in pirate_main
    pirate.torrent.save_torrents(choices, results, args.save_directory)
TypeError: save_torrents() missing 1 required positional argument: 'folder'
```

Also, where is the log file on the mac?

### PR DESCRIPTION
**Pull request by vikstrous**
fix #95

I haven't had a chance to test this at all because I recently switched to nixos and I'm still figuring stuff out, but this should work. Can someone confirm that it works? Unfortunately we don't have tests for this.

### CODE REVIEW

**Comment by rnhmjoj** [comment]
It's ok however I haven't been able to find a single torrent that was cached by torcache in the top 100 ones. Maybe we should use something else to download the files.

**Comment by rnhmjoj** [comment]
I use this nix expression to test pirate-get on NixOS:
```nix
{ pkgs ? import <nixpkgs> {} }:
with pkgs.lib;

pkgs.python3Packages.buildPythonPackage {
  name = "pirate-get";
  src = ./.;

  doCheck = false;

  buildInputs = with pkgs.python3Packages;
    [ colorama beautifulsoup4
     veryprettytable flake8
    ];

```
Save it in the project root as `shell.nix`, run nix-shell and your ready to go.

**Comment by vikstrous** [comment]
Thanks for the nix expression! I think torcache.net might be dead. Their whois still exists, but their domain doesn't point at anything.

**Comment by vikstrous** [comment]
Update: Done. Thankfully I documented the release process so it was much simpler this time: https://github.com/vikstrous/pirate-get/wiki/Releasing

**Pull request merged**
